### ISSUE TITLE
Epic: Configure iiif in Adventist

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#278]
# Summary

Once IiifPrint is installed, we should communicate with the client to clarify which configurable features to enable. 

Give the client the options or review their SOW (look in google drive or ask Jill), and update this ticket with what needs to be done.

For PDFs that are split into multiple images (and therefore child works), we don't want those child works to show up in the search.  In other words the expectation is that when searching via `/catalog` they are expecting to find a complete book instead of a heap of loose leaf pages.

We will also need to account for advance search.  The IIIF Print gem recommends using the changes to the [IiifPrint::CatalogSearchBuilder](https://github.com/scientist-softserv/iiif_print/blob/bce83fe49b81b4862ed02e183a3ff240c8e7a5dc/lib/iiif_print/catalog_search_builder.rb).  However, in Adventist they have set the [`CatalogController.search_builder_class` to `AdvSearchBuilder`]( https://github.com/scientist-softserv/adventist-dl/blob/21275bdcf5f50356e0b96ab5d1176195c4effb89/app/controllers/catalog_controller.rb#L50).

*Note:* We will like want to have the `AdvSearchBuilder` inherit from the `IiifPrint::CatalogSearchBuilder`; but we'll need to be cautious about the order of the processor chain because Jeremy has seen the wrong order bungle up queries.

Other considerations will be how we do or do not show the child works in the adminsitrative interface.  Those should be future tickets, as that will be a lower priority than the world-facing tasks.

# Acceptance Criteria

- [ ] #286
   - [ ] This might require us to create a custom work (ChildPage perhaps?)
   - [ ] We'll need to configure each non-child model to split PDF pages to the ChildPage
- [x] #287
- [ ] #293
- [ ] Configure Tesseract for OCR #248 
- [x] #294

# Screenshots or Video

# Testing Instructions

# Notes

slack convo: https://assaydepot.slack.com/archives/C0313NJV9PE/p1677254213843829

**Comment by jillpe** [comment]
Katharine wants it to apply to all models. We established a guiding principle in yesterday's meeting that we can base the configurations off of: https://assaydepot.slack.com/archives/G0311DN2YCA/p1677618806674919

**Comment by ShanaLMoore** [comment]
per Jeremy: try making the adv search builder in adv inherit from the iiif_print one, to make the parent-only return possible.

**Comment by ShanaLMoore** [comment]
client doesn't only wants txt derivatives for image model. 

apply pdf splitting to all. 

enable parent_only

consider persisting search from catalog to UV: 

LV PR that enabled this: https://gitlab.com/notch8/louisville-hyku/-/commit/7c584b2fc58bd271db38d7ec5c2aba74a43c0ee2
Reason that LV removed it: https://gitlab.com/notch8/louisville-hyku/-/issues/122#note_994550119

**Comment by jillpe** [comment]
Blocked #286 needs rework

**Comment by ShanaLMoore** [comment]
closing per https://github.com/scientist-softserv/adventist-dl/issues/286#issuecomment-1514904337
