### ISSUE TITLE
Spike: OCR search not working

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#319]
# Story

Per Katharine, 

" I searched for a word in the UV and got no results despite seeing it on the page. This work has split into pages. Can you determine if something is wrong with the OCR search in viewer, or are we still waiting on the work to process?"

# Acceptance Criteria

- [ ] Can we duplicate the issue
- [ ] Can we define the resolution for the specific work that isn't correct

# Screenshots / Video

link to example: https://adl.s2.adventistdigitallibrary.org/concern/published_works/20214381_an_appeal_to_the_youth_funeral_address_of_henry_n_white?locale=en

generated ocr: [8b-txt.txt](https://github.com/scientist-softserv/adventist-dl/files/11029761/8b-txt.txt)

Search for "Youth" returned no results: 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/10081604/226649184-0a0945d9-7d09-4d66-9dcd-772efda2ff72.png">

When looking at this solr doc in rancher, I'm not seeing all_text_tsimv

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10081604/226649399-87d3dfda-a7ca-4e79-bd54-9cf2620f0048.png">

Confirmed that this work type has ocr turned on: https://github.com/scientist-softserv/adventist-dl/blob/main/app/models/published_work.rb#L31

# Testing Instructions and Sample Files

- create a work via bulkrax or manually
- wait for sidekiq to complete and verify that ocr gets generated. 
  - You can see the words it found by clicking on the action dropdown. Select download as txt
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/10081604/226650391-b451a4b2-6ffd-4f44-b274-069b86205690.png">

- [ ]  a user should be able to search the UV and catalog, for the generated ocr words

# Notes

This issue was reported before sidekiq completed its jobs, so it may be a timing issue. 

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/10081604/226649845-8b349015-0197-4c28-b030-c092703342aa.png">

**Comment by ShanaLMoore** [comment]
## TODO: 

validate if this is still an issue locally.

**Comment by kirkkwang** [comment]
OCR seems to be working, though I tried the [sample data](https://github.com/scientist-softserv/adventist-dl/issues/337#issuecomment-1495012610) and it's very inconsistent.  

Very poorly OCR'd example (text and image):
[08-txt.txt](https://github.com/scientist-softserv/adventist-dl/files/11151686/08-txt.txt)
![a85818dc-08ae-4b8a-bbab-8fcb43004255-page3](https://user-images.githubusercontent.com/19597776/229881607-d6db8294-40dd-4537-a60e-1fc1bf27f152.jpg)

Good OCR example (text and image):
[cc-txt.txt](https://github.com/scientist-softserv/adventist-dl/files/11151838/cc-txt.txt)
![276df1c8-8628-462f-8f16-1afce89851e7-page1](https://user-images.githubusercontent.com/19597776/229884744-fdc18e3f-56ef-4e06-b913-f028ac7cefca.jpg)

Also, searching from the parent doesn't seem to be working:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/19597776/229885171-a4322e1a-d641-4a6d-b24e-ba00d8f5e5c1.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/19597776/229885052-25a7a821-6d5b-4b90-b3de-05e632c73b30.png">

**Comment by ShanaLMoore** [comment]
blocked because we may need to reindex staging

**Comment by ShanaLMoore** [comment]
OLD DATA WILL NOT WORK until staging's reindexing succeeds. Until then, please only QA this using new data on the sdapi tenant.

**Comment by ShanaLMoore** [comment]
On [sdapi](https://sdapi.s2.adventistdigitallibrary.org/concern/theses/20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t?locale=en) I searched for the work "thesis" from this parent work. and it returned matches: 

## OCR Search
searched for the word 'thesis'

### UV
![Image](https://user-images.githubusercontent.com/10081604/230500917-a72ba155-c7be-4741-be41-032079e075fd.png)

### CATALOG

only the parent returned 

![Image](https://user-images.githubusercontent.com/10081604/230501314-16011e66-23bd-413b-bad1-b485ef880de4.png)


## METADATA SEARCH
search for identifier **20121820**

## UV



![Image](https://user-images.githubusercontent.com/10081604/230501832-0429fb94-38d5-4dd6-81ba-05b64a9ee7d3.png)




## CATALOG

only returned parent search

![Image](https://user-images.githubusercontent.com/10081604/230501676-20c3229e-a4f1-4e2c-84b0-d0a6aa449678.png)

**Comment by KatharineV** [comment]
I'm testing this with SDAPI staging and a [work ](https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/22253132_spectrum_winter_1969?locale=en)I uploaded yesterday. 

From the parent work, I don't see the option to download txt, but child works were generated, so I'm going to push forward on this test and see what happens.

![Image](https://user-images.githubusercontent.com/118196520/230611811-68535f93-5c3d-4418-ad2f-a4bee38c1fb8.png)

Child works do allow txt download. 

![Image](https://user-images.githubusercontent.com/118196520/230611921-fef10eea-e9ce-4da8-bfb5-c0289a90f999.png)

From the child work txt file, I see that the word "Christian" was recognized. I can search that in the parent work UI and receive results.

![Image](https://user-images.githubusercontent.com/118196520/230612233-ada2a757-19a2-457e-b927-6022a91f1660.png)


I also searched for an unusual word that appears on the same child page--"discursive." The catalog search only returns the parent. So, all seems to be working as expected for the OCR search with this test work!


![Image](https://user-images.githubusercontent.com/118196520/230612437-b975f934-9032-4d78-a5bf-9faea9b57133.png)

**Comment by laritakr** [comment]
> From the parent work, I don't see the option to download txt, but child works were generated, so I'm going to push forward on this test and see what happens.

We do not OCR & other derivatives on the PDF so this is to be expected. From what I remember, we only split the pdf and make a thumbnail.

**Comment by KatharineV** [comment]
> We do not OCR & other derivatives on the PDF so this is to be expected. From what I remember, we only split the pdf and make a thumbnail.

Thanks for that explanation. I was just following the testing instructions, which must be based on a previous configuration where the TXT derivative was created. 

I also thought ticket 293 left some derivatives other than thumbnail for PDF. I'm rereading 293 right now, and it looks like other derivatives would be expected. I'm obviously not tracking the changes and what the final configuration should be, but I'll take my confusion to the other ticket.

**Comment by laritakr** [comment]
Yes, one problem with all of these overlapping tickets is that things change rapidly and it's hard to keep track of everything! A lot of the derivatives were removed because they take so much time to generate during ingest.

Derivatives ARE configurable and will become more so with upcoming work. If something different is needed, that configuration will need to be clarified. It's easier to do that when you can see what is there and ask questions based on actual use.

**Comment by ShanaLMoore** [comment]
Blocked from verifying: this requires a reindex.

**Comment by KatharineV** [comment]
Tested on production with the [work ](https://adl.b2.adventistdigitallibrary.org/concern/published_works/22253132_spectrum_winter_1969?locale=en)that Shana suggested above. A search for OCR'd text did return a result as expected. Yay!



![Image](https://user-images.githubusercontent.com/118196520/230918340-52f66b2d-10a5-4946-8133-0c9b695e5ba1.png)
