### ISSUE TITLE
EPIC: Import Optimization with Out of Band Processing

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#330]
The goal of this epic is to adjust the derivative “creation” process.

At present Hyrax creates a `FileSet` for each file added to a work either via the UI or via batch processing.  We then process each original file of a `FileSet` creating derivative files that we attach to that `FileSet`.  This is all done “in-band”, which can be non-performant for large imports.

To speed up the imports we can:

-   add more resources to the import system
-   perform “out of band” processing to generate derivatives

By introducing the idea of the “out of band” processing, we break the fundamental assumption of Hyrax’s derivative generation.  Namely that it will take a `FileSet` and create all the necessary derivatives.  Instead, with pre-processing, we are now saying “There may already exist a derivative for this `FileSet`, attach that instead.”

Instead of having one conceptual “Create Derivatives” function we are looking to have three:

-   **Pre-processing:** doing out of band work to create derivatives.
-   **Locating:** Finding the existing derivatives (or possibly indicating that we’d create new ones).
-   **Applying:** Taking the found derivative and adding it to the correct FileSet.

We have a “prior art” instance of *Pre-processing* in the [SpaceStone](https://github.com/scientist-softserv/space_stone) Ruby gem.  That gem is code that runs in <abbr title="Amazon Web Services">AWS</abbr> Lambdas to pull data from Internet Archive (per the client’s previous storage), split apart the PDFs, create <abbr title="Optical Character Recognition">OCR</abbr> derivatives of each page, and create thumbnails.

Further, we have “prior art” for *Locating* and *Applying* `.hocr` files in [NNP’s Tesseract module](https://github.com/scientist-softserv/nnp/blob/78206122b9796a79f07f349ef27babc167006f6d/app/services/tesseract.rb); responsible for first looking for a remote `.hocr` and failing that generating the `.hocr` file.

We have some logic for finding the *Pre-processing* files in [NNP’s DistributedRemoteDownloader](https://github.com/scientist-softserv/nnp/blob/78206122b9796a79f07f349ef27babc167006f6d/app/services/distributed_remote_downloader.rb).

Those are specific implementations that demonstrate some of the necessary concepts.  However, those are different from the immediate needs of Adventist and the general needs of other clients.

<a id="org110fc7f"></a>

# Scenarios

In terms of *Pre-Processing* we need the following:

```gherkin
Scenario: Pre-processing
Given an identifier for a FileSet
  And a URL to the original file
  And the file is a PDF
When I pass the identifier and URL to an AWS lambda
Then the Pre-processer Lambda will create one <JPG> per PDF page
  And the Pre-processer Lambda will create one HOCR per PDF page
  And the Pre-processer Lambda will create one Thumbnail per PDF page
```

In terms of *Locating* we need the following:

```gherkin
Scenario: Locating derivatives that were pre-processed
Given an identifier for a FileSet
  And the Pre-processer Lambda has processed the FileSet
When I attempt to locate the <JPGs, HOCRs, Thumbnails> for the split pages
Then I will get the location of the S3 files

Scenario: Locating derivatives that were not pre-processed
Given an identifier for a FileSet
  And the Pre-processer Lambda has not processed the FileSet
When I attempt to locate the <JPGs, HOCRs, Thumbnails> for the split pages
Then I will not get a location of the S3 files
  And I will get a “location” that will indicate to use the default Hyrax derivative generation
```

In terms of *Applying* we need the following:

```gherkin
Scenario: Applying derivatives that were pre-processed
Given an identifer for a FileSet
  And the Pre-processer Lambda has processed the FileSet
When I attach the located <JPGs, HOCRs, Thumbnails> for the split images
Then I will fetch those derivatives from S3
  And attach those derivatives to the FileSet

Scenario: Applying derivatives that were not pre-processed
Given an identifer for a FileSet
  And the Pre-processer Lambda has not processed the FileSet
When I attach the located <JPGs, HOCRs, Thumbnails> for the split images
Then I will generate those derivatives
  And attach those derivatives to the FileSet
```

One consideration is that Hyrax has implicit derivatives that are named concepts; for the above features we need to expose those named concepts.  Namely, how do I locate and apply the thing called `thumbnail`?

<a id="org11acab4"></a>

# Task Breakdown

Adventist S3 Convention: there’s an AARK unique for each work.  Write files there.

-   [ ] Spike: Establish the S3 bucket organization structure with consideration for: identifier, original file, and derivative type.
-   [ ] Merge Samvera::Derivatives configuration concerns with IiifPrint configuration
    -   The APIs are not part of production code and provide the named building blocks for this work.
-   [ ] Rename IiifPrint to Samvera::Derivatives
    -   IiifPrint seems to be a bit of a misnomer; we’re talking about how we want to make derivatives.
-   [ ] Adventist: Read OAI feed, sending non-thumbnail (and non-reader.pdf) files to S3
    -   We need to write a function that will read an OAI feed and post that to the Pre-processor Lambda.
-   Space Stone:
    -   [ ] Split PDF apart
        -   Consideration: how is this logic the same/different from what we have in IIIF Print?  What does a canonical function look like?
    -   [ ] Run OCR on individual pages
        -   Consideration: how is this logic the same/different from what we have in IIIF Print?  What does a canonical function look like?
    -   [ ] Generate a thumbnail for each page
        -   Consideration: how is this logic the same/different from what we have in Hyrax?  What does a canonical function look like?
-   Iiif Print:
    -   [ ] Create general S3 locator function
        -   This needs to account for the derivative type (e.g. `hocr`, `thumbnail`, `splits`, etc) and the identifier.
    -   [ ] Create general S3 applicator function
        -   This needs to write the file to the location expected by Fedora.  This is behavior that has prior art.
    -   [ ] Spike: Resolve whether S3 locator pulls file down or if that is the applicator’s purview

**Comment by jeremyf** [comment]
With a bit of retrospective, the most critical decision I made early was to name each derivative (e.g. `:hocr`, `:text`, `:monochrome`); after all we have a named “file” for each of those.  In doing so, I have a conceptual object in which to organize my code.

Yesterday, I also turned a major corner on this project.  In the morning I sat down and started writing narrative descriptions in the [README of SpaceStone::Derivatives](https://github.com/scientist-softserv/space_stone-derivatives/blob/main/README.md).

This lead to naming the concepts of the [SpaceStone::Derivatives::Manifest](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/manifest.rb) and the [SpaceStone::Derivatives::Repository](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/repository.rb).  With those names, I had eliminated some of my mental barriers regarding the various layers of abstractions and mappings.

A second revelation was when I stepped away from the code and started verbally narrating.  I had hit a minor mental block, fixating on a low-level detail to which I had lost the thread to the larger feature requirement.  The inspiration came when I named the `SpaceStone::Derivatives.pre_process_derivatives_for` method.

That named method gave me the clear mental map into the process steps.

Immediately, I knew I would need to resolve the dependency graph of derivatives.  I first started with a validator function that could process a hash.

Then I thought about how I would perform the sequence.  Which introduced the idea of the [SpaceStone::Derivatives::Chain](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/chain.rb).  I moved the validator into that class and began working on a sequencer function; likewise the sequencer would process a hash.  As I delved deeper, the Validator and Sequencer were performing duplicate logic.

I had begun stenciling in the [SpaceStone::Derivatives::Types](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/types.rb) in an effort to play with the conceptual idea.

I ripped out the validator and settled on  [SpaceStone::Derivatives::Chain::Sequencer](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/chain.rb#L49-L92); again something I could test with a Hash that had symbol keys and values that were arrays of symbols.

With the sequence of derivative generation resolved, I set about the conceptual [SpaceStone::Derivative::Processor](https://github.com/scientist-softserv/space_stone-derivatives/blob/e373fccc20f1115fca9137beb40140d59eae9c57/lib/space_stone/derivatives/processor.rb).  It began it’s life named “PreProcessor” but as I was writing the documentation, I wrote “send the pre\_process! message to the each of the types in the chain.”  With the word “message”, I realized I could use a dispatching strategy (e.g. `send(message, repository: repository)`).

A key design consideration has been quick and easy testing.  And during the day’s development, I refactored the method signatures a few times.  Each time spending a few minutes changing and running tests.

For 2023-03-29 I plan to look into the following:

-   The Repository needs to consider it’s file storage strategy.  I have some ideas and will likely be implementing an adapter pattern.
-   I need to switch the current ported over derivatives to the new `SpaceStone::Derivatives::Types`.
-   I feel close to being able to wire this back into IIIF Print; however I think that is a lower priority.
-   I wrote `Manifest::FileLocationSet` as a named parameter.  I’ll need to play with that a bit.

More important is getting the entire pre-processing ready to run via SpaceStone proper (e.g. AWS Lambda).

As an added benefit, I believe that `SpaceStone::Derivatives` is almost certainly vendor agnostic (managed instead by the yet to be made repository file storage strategy).

I continue to rely on local tests, both style guides and rspec.  These run each time I commit code and each time I push code to the Github.

**Comment by jeremyf** [comment]
Inspired by LeaAnn’s “Project and Task Breakdown” presentation on <time datetime="2023-03-30">Thursday</time>, I wanted to write up the task breakdown/algorithm:

For the pre-processing in AWS:

1.  Check if the file exists in the expected AWS location.  If it does, return a “handle” to it.
2.  Else, if it doesn’t and the manifest says it has a remote URL, attempt to GET it.
    -   On a 404, log a warning and return “nil”
    -   On a 2xx, copy it into the expected location, and return the “handle”
    -   On any other status, log an error and raise an exception.
3.  Else, if it can’t be remotely fetched, attempt to Generate it.
    -   On a failure to generate, log an error and raise an exception.
    -   On a success but there’s no file, log an error and raise an exception.
    -   On a success with a file, move the file to the expected location and return the “handle”.

What is the file “handle”?  Perhaps the path name.

I also say “AWS” but this is really the pre-processing environment; a “loading dock” if you will.

In the above case, we only want to verify that we have a “handle”.  If the “handle” does not exist, that is an error in processing the manifest.  Put another way, once we’ve processed the manifest, we need to audit it’s integrity.

**Comment by jeremyf** [comment]
Thoughts from 2023-04-05:

I have a working proof of concept for monochrome and hocr.  Now I need to look into PDF splitting.  I start with an original file that is a PDF.

I want to make a thumbnail of the PDF.  I also want to split the PDF.  When I split the PDF, I’m probably going to create a manifest for each of the pages.  And then feed those manifests to the processor.

I likely want the original PDF and the split files to be in a similar location (for easier finding).  What would that look like?

`/path/to/:parent_id/:original_file/<original>`
`/path/to/:parent_id/:original_file/pdf_split/:index/<image>`
`/path/to/:parent_id/:original_file/pdf_split/:index/<monochrome>`
`/path/to/:parent_id/:original_file/pdf_split/:index/<hocr>`

As written, I do not have a consistent predictable temporary directory creation process.  The input for derivatives is:

1.  Parent ID
2.  Original Filename
3.  Original URL
4.  <Derivative> URL
5.  Working directory…if it exists, use that, otherwise, create a new one and assign.

**Comment by jeremyf** [comment]
<time datetime="2023-04-05">This morning</time> I realized that I need to lean into the `Chain` concept.  Namely, because of the async nature of <abbr title="Amazon Web Services">AWS</abbr>, I need to process the chain as follows:

```gherkin
Given a chain of <A>, <B>, <C>, and <D>
When I “schedule” <A>, I need to provide the chain.
Then as part of completing <A>, it “scheduless” <B>.
```

In the above example, let’s say that `<B>` is the `:split_pdf`.  It is responsible for launching the “sub-processes” of `:ocr`.  An assumption is that the given `Chain` creates the files that later links are dependent on.  In other words, the sub-processes of `:ocr` are not dependents of the above `<C>` nor `<D>`.  And the sibling processes of split pages are not dependent on each other.

Ideally, we don’t need to notify the parent `<B>` that all children are done.  Due to convention, `<B>` might want to write it’s manifest of indices that it wants to generate.

```gherkin
Given a parent process <B>
And the child chain <Ba>, <Bb>, <Bc>
And the children <0>, <1>, <2>
When I “schedule” <0>, I need to provide the chain.
Then as part of completing <0>’s <Ba>, it “schedules” <Bb> for <0>.
```

Critical in this is once I start processing an “original” manifest, I need to preserve the storage “handles” for both the “local” and the “remote”.  Those handles, along with the chain, help the processing locate either pre-existing files or fetch from a common remote location.

I also need the “processing queue” to provide an in-line option or to send things to <abbr title="Amazon Web Services">AWS</abbr>’s <abbr title="Simple Queue Service">SQS</abbr>.

**Comment by jeremyf** [comment]
# June 5 to June 9 Sprint Adventist Tasks


## OAI -> CSV

We need to ensure that our conversation with Katharine is “encoded” in the CSV logic.  We have PDF and we have Image as the original file.  We also can ignore the Periodical images et. al (because those images are the representative image which Hyku does not account for).

Our plan is to add the archival, reader, and txt as three FileSets on a work.  The archival we will pre-process derivative generation.  The reader we only want thumbnails.  And the text we can use Hyrax::FileSetDerivativesService as written.

We need to somehow communicate that the reader fileset does not split nor have much of any other derivatives.


## CSV -> SpaceStone

This was pushed up by Rob and merged by Jeremy; he’s working through the logic and how we’ll map accordingly.  We can likely re-use the thumbnail for the reader; this might mean copying the original thumbnail twice.


## SpaceStone does it thing

We need to deploy the latest SpaceStone.  Jeremy needs to be able to do this, as does Kirk.  First, we try Kirk as he has successfully deployed once; and we likely won’t need more deploys of SpaceStone.

We want to review the SpaceStone S3 buckets to ensure they are structured as intended.


## IIIF Print pulls from SpaceStone

With the latest changes, which are pending review but will be merged by EoD Tuesday, we are prepared to update Adventist to use the Derivative Rodeo enabled IIIF Print.


## Configure Adventist’s DerivativeRodeo

We need to update Adventist’s IIIF Print gem to get the Derivative Rodeo; this will help inform how we post to SpaceStone (as there’s a configuration assumption which is marked as a TODO)
