### ISSUE TITLE
☄️ Epic: UV upgrades

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#359]
# Updated Ticket Instructions: May 18, 2023
## Summary
This is an epic 

## Accepted Criteria
- [x] #417
- [x] #418
- [x] #419
- [x] #420

## Notes

--------------------------------------------------------------------------------------------------------------------------
## Summary
Possible round of work for the future to build out UV on ADL tenants. Wishlist shown in the Accepted Criteria

## Accepted Criteria
~~- [ ] Enable the UV to support multiple search terms~~
~~- [ ] Enable the UV to deliver individual pages as quickly as it does on the example site~~
  - will be covered with derivative rodeo
~~- [ ] Enable individual pages to show with human-readable page numbers, like the example site~~
- [ ] Enable the UV to deliver video--either from an attached file or from YouTube like the example site
- [ ] Enable the UV to deliver audio--if possible
- [ ] Increase the size of the UV on ADL tenants so it displays pages larger upon first load, like it does on the example site
- [ ] Add Download features to the UV on ADL so users can download individual pages or view all pages as PDF/TXT from the action button in the bottom left corner of the UV (see other screenshot for features we'd like, if they're doable)

**Comment by KatharineV** [comment]
Hi team, I'd like to add this ticket to the priority list for our next sprint, if it can fit. I know some of it is already addressed/being addressed, like the human-readable page numbers. Thanks!

**Comment by jillpe** [comment]
"Enable individual pages to show with human-readable page numbers, like the example site" is resolved

**Comment by ShanaLMoore** [comment]
QA blocked until staging reindex completes

**Comment by KatharineV** [comment]
Tested on ADL Staging, and all of the requested features are working as expected. I tested using the following works:
Generic work with embedded video/audio from YouTube https://adl.s2.adventistdigitallibrary.org/concern/generic_works/4b63536d-fbe2-4beb-baf9-2b2150281b72?locale=en 
Published Work that demonstrates the larger UV size and full download options https://adl.s2.adventistdigitallibrary.org/concern/published_works/529f7a71-07af-4c1e-b005-de62726442f8?

These updates look great.
