### ISSUE TITLE
Script to pull from solr

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/adventist-dl#37]
# Summary

Create a chron job that runs daily pulling the following fields from solr: 
- hyku identifier
- ark_ID
- Time stamp field on solr

Run job once and then confirm that it would work to run daily and not slow down the system.

## Tasks

- [X] Create script for initial query (see https://github.com/scientist-softserv/adventist-dl/pull/140)
- [ ] Determine what to do with output of script
- [ ] Implement decision regarding output of script
- [ ] Run script on production; review utilization details for when the script was running
- [ ] Add script to crontab

**Comment by DiemBTran** [comment]
E Koester - April 2022

---
What is the status of this? This feature will allow us to audit what is on Hyku quickly. Without it, several days of constant querying of the OAI service is required.

**Comment by DiemBTran** [comment]
E Koester - July 2022

---

Let's just drop this. I am able to perform this sort of task directly in development and if needed can create the required script to enable this in production.

**Comment by jeremyf** [comment]
Per message from Eric; I'm closing this.
