### ISSUE TITLE
☄️ Go Live Checklist for Adventist Pre-Processing

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#500]
The following items are required as part of starting the pre-processing of Adventist's objects (Note this is a living list, we may read it and need to add more):

- [ ] Confirm that Adventist wants to split PDFs into JPGs.  (The goal is to minimize storage costs.)
- [ ] Ensure that Adventist’s SpaceStone configuration is splitting pages into JPGs
- [ ] Ensure that Adventist’s DerivativeRodeo (by way of IIIF Print) configuration is looking for JPGs  
- [ ] Create a “production” environment for SpaceStone, using Adventist’s AWS ecosystem.
  - [ ] How do we manage those credentials?
  - [ ] Ensure the credentials, buckets, and queues of SpaceStone are reflected in the configurations for
    - [ ] Sending the pre-processed entries up to SpaceStone (code in Adventist repository)
    - [ ] Connecting the DerivativeRodeo to download the pre-processed entries (code in Adventist repository)
- [ ] Pre-process 50 files with Serverless Profiling.  (The goal is to identify the pre-processing cost of a larger sample.)
- [ ] Pre-process another 50 files with Serverless Profiling.  (Compare against the previous sample.  In part because AWS expenses report on a 24 hour cycle, and that could wrack up a lot of costs if we have a non-optimized pre-processing pipeline.)
 
Once we've met the above, we want to clear with @KatharineV the likely cost as well as any timing considerations.  For example, we have a process to generate a CSV of all of the files in the OAI feed and how to sort them to their correct slot.  However, there's work being done on the OAI feed, so we want to make sure we catch anything that might be missing.
