### ISSUE TITLE
☄ EPIC: Install Knapsack/Upgrade Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#541]
# TODO 

- [x] Create a knapsack for adventist, put it up in a new repo
- [x] Go through differences between Hyku v4.0.0~55 and Adventist moving items in to either Hyku main or the knapsack as approriate

  - [x] #546
  - [x] #544
  - [x] #550
  - [x] #543
  - [x] #547
  - [x] #548
  - [x] #549
  - [x] #542
    - [x] #553
  - [x] #551
    - [ ] #556
- [x] https://github.com/scientist-softserv/adventist-dl/issues/537
- [x] https://github.com/scientist-softserv/adventist-dl/issues/538
- [x] https://github.com/scientist-softserv/adventist-dl/issues/540
- [x] fix Bugs
- [x] #552

# NOTES

https://jamboard.google.com/d/1ZjyNbU_CcRj0S9QkS104AFcDIoXQ0sMmFXP1_TmJcco/viewer?f=0

- [x] Upgrade Hyku
**ADL:** 
- hyku version: [3.0.1](https://github.com/scientist-softserv/adventist-dl/blob/main/config/initializers/version.rb#L2)
- Hyrax version: [2.9.6](https://github.com/scientist-softserv/adventist-dl/blob/main/Gemfile.lock#L504)
**Knapsack:**
- hyku version: [5.1.0](https://github.com/samvera/hyku/blob/adventist_dev/config/initializers/version.rb#L2)
- Hyrax version [3.5.0](https://github.com/samvera/hyku/blob/adventist_dev/Gemfile.lock#L579)

**Comment by ShanaLMoore** [comment]
related SLACK convo: https://assaydepot.slack.com/archives/C0311DN2YCA/p1695283933766499

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/9faeca14-e903-4eb0-95a8-2affb4d842e5)

**Comment by ShanaLMoore** [comment]
TODO: correct any client feedback and deploy to prod!
