### ISSUE TITLE
Epic: CSV Importer that accepts DC

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#75]
# Summary
Overarching Goal: Enable a CSV importer in Bulkrax with their current mappings that accepts Dublin core.

[Current Mappings](https://docs.google.com/spreadsheets/d/1GEsyaFNias1JmnAkRLZbMYsBIaV-1rxl/edit#gid=1720793301)

Adventist would like functionality to include round-trip import/export.

https://github.com/samvera-labs/bulkrax/wiki/Configuring-Bulkrax#field-mappings

# Acceptance Criteria

- [ ] CSV Parser configured using Bulkrax importer
- [ ] [Bulkrax is updated to latest version](https://gitlab.com/notch8/adventist-dl/-/issues/151)
- [ ] [New metadata mappings created to parse new fields](https://gitlab.com/notch8/adventist-dl/-/issues/152)
- [ ] [New parser built in Bulkrax](https://gitlab.com/notch8/adventist-dl/-/issues/153)
- [ ] [Admin-side dashboard UI elements implemented](https://gitlab.com/notch8/adventist-dl/-/issues/154)

# Screenshots or Video

# Testing Instructions

# Notes
- Can you confirm the above sheet includes your current mappings?

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked Items:

Relates to:

- Create .csv parser for all Tenants
- [3] Bulkrax updated to latest version
- Assigned to Braydon Justice
- [3]DC term metadata mapping
- Assigned to DeonFranklin
- [3] Enable CSV parser enabled in Bulkrax
- Assigned to Jeremy Friesen
- Admin-side dashboard UI elements implemented
- Revisit Parser Mappings with 2022-10-27 Information and Later

**Comment by DiemBTran** [comment]
Related MR:

[updated csv mappings to QDC headings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/204)
!204
[Updated shared parser mappings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/209)
!209

**Comment by DiemBTran** [comment]
Jill Peterson - Aug 2022

---

It looks like we will need to add some fields to be mapped:

- [ ] Citation
- [ ] Contributors
- [ ] Alt. Contributors
- [ ] Edition
- [ ] English Title
- [ ] English Translation
- [ ] Genre
- [ ] Issue
- [ ] Notes
- [ ] PageRange
- [ ] Provinance
- [ ] Publisher
- [ ] RefID
- [ ] SeriesOrCollection
- [ ] SortDate
- [ ] Subtitle
- [ ] TableOFContents
- [ ] Topic Keywords
- [ ] TopicConference
- [ ] TopicSubjectHeadings
- [ ] TopicOrganizations
- [ ] TopicPeople
- [ ] TopicGeographic
- [ ] Transliteration Title
- [ ] TypeOfResource
- [ ] Url
- [ ] Volume
