### ISSUE TITLE
Home Page Epic

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#76]
# Summary
**Overarching Goal:** Create a homepage that draws inspiration from the examples below, is more image-heavy/user friendly, has and 'About Us' blurp, and a News Update widget.

Adventist wants to update their homepage to be more image-heavy and friendly for the user. They would also like to have and 'About Us' text on it, and a Widget for News Updates that links to an external site they create. They are taking inspiration from:

- [Atla Digital Library](https://dl.atla.com/)
- [UCLA Library Digital Collections](https://digital.library.ucla.edu/)
- [Anderson University Digital Archives](https://au-archives.hykucommons.org/?locale=en)
- [British Library's Research Repository](https://bl.iro.bl.uk/)

# Accepted Criteria

- [ ] [Home Page Wireframes complete](https://gitlab.com/notch8/adventist-dl/-/issues/139)
- [ ] [Updated Home Page](https://gitlab.com/notch8/adventist-dl/-/issues/140)
- [ ] [Updated Widget for News](https://gitlab.com/notch8/adventist-dl/-/issues/141)
- [ ] [Updated home page text per tenant](https://gitlab.com/notch8/adventist-dl/-/issues/87)
- [ ] [Made Banner Image respect a new Banner Image File](https://gitlab.com/notch8/adventist-dl/-/issues/111) 
- [ ] [Toolbar for editing content not displaying properly on the Settings -> content block](https://gitlab.com/notch8/adventist-dl/-/issues/81) 

# Notes

**Comment by DiemBTran** [comment]
Linked Items:

Relates to:

[[3] Home Page Wireframes](https://gitlab.com/notch8/adventist-dl/-/issues/139)
#139
[Update Home Page](https://gitlab.com/notch8/adventist-dl/-/issues/140)
#140
[Update Widget for News](https://gitlab.com/notch8/adventist-dl/-/issues/141)
#141
[Update home page text per tenant](https://gitlab.com/notch8/adventist-dl/-/issues/87)
#87
[Make Banner Image respect a new Banner Image File.](https://gitlab.com/notch8/adventist-dl/-/issues/111)
#111
[Toolbar for editing content not displaying properly on the Settings -> con](https://gitlab.com/notch8/adventist-dl/-/issues/81)
#81

**Comment by DiemBTran** [comment]
Katharine Van Arsdale - Oct 2022

---

We're finding that an external news site is out of scope for our team right now. We'd like to substitute that homepage widget with one that can draw on our social media accounts, if possible. We have Twitter and Instagram. Here's a Hyku example I saw today that links to Twitter, which we like in concept if not in final placement on the homepage. https://archive.kingsfund.org.uk/
